-- SQL script to initialize the WorkBuddy database in PostgreSQL

-- Create the database (if not exists)
CREATE DATABASE workbuddy;

-- Connect to the workbuddy database
\c workbuddy;

-- Create tables (these will be auto-generated by Hibernate, but we can define them explicitly if needed)

-- Example table structure (for reference only)
-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     username VARCHAR(50) UNIQUE NOT NULL,
--     email VARCHAR(100) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE workers (
--     id SERIAL PRIMARY KEY,
--     user_id INTEGER REFERENCES users(id),
--     name VARCHAR(100) NOT NULL,
--     phone VARCHAR(20),
--     address TEXT,
--     skills TEXT[],
--     is_active BOOLEAN DEFAULT true,
--     rating DECIMAL(3,2) DEFAULT 0.00,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE services (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     description TEXT,
--     base_price DECIMAL(10,2),
--     category VARCHAR(50),
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE bookings (
--     id SERIAL PRIMARY KEY,
--     customer_id INTEGER REFERENCES users(id),
--     worker_id INTEGER REFERENCES workers(id),
--     service_id INTEGER REFERENCES services(id),
--     booking_date DATE NOT NULL,
--     booking_time TIME NOT NULL,
--     address TEXT,
--     status VARCHAR(20) DEFAULT 'pending',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE payments (
--     id SERIAL PRIMARY KEY,
--     booking_id INTEGER REFERENCES bookings(id),
--     amount DECIMAL(10,2) NOT NULL,
--     payment_method VARCHAR(20),
--     transaction_id VARCHAR(100),
--     status VARCHAR(20) DEFAULT 'pending',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Note: With Spring Boot and Hibernate, these tables will be auto-created based on your entity classes.
-- This script is provided for reference only.